---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: 3.1.5
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:fluxcd/helm-operator-get-started
    path: charts/podinfo
    ref: master
  valuesFrom:
  - secretKeyRef:
      name: message
      key: SecureString
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 3.1.5
    replicaCount: 1
    hpa:
      enabled: false
